#
# Settings specific to my personal machines
#

# Mail Stuff
export MAILUSER="jesse"
export MAILNAME="Jesse Morgan"
export MAILHOST="jesterpm.net"
export MAIL=$HOME/.maildir/
export MAILDIR=$MAIL


export AWS_ACCOUNT_ID=206578203396
