#
# Settings specific to my personal machines
#

# Mail Stuff
export MAILUSER="jesse"
export MAILNAME="Jesse Morgan"
export MAILHOST="jesterpm.net"
export MAIL=$HOME/.maildir/INBOX
export MAILDIR=$MAIL

# PATH
export PATH=$HOME/opt/bin:$PATH

