# Change prefix to C-q
#unbind C-b
#set -g prefix C-q
#bind-key C-q send-prefix

# Don't slow down my escape key...
set -s escape-time 0

# Enable mouse support
set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -in -selection clipboard"

# Split commands
bind / split-window -h
bind '"' split-window -v

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

%if "#{==:#{host},cobalt}"
set -g status-style bg=cyan
%elif "#{==:#{host},cadmium}"
set -g status-style bg=green
%elif "#{==:#{host},aurum}"
set -g status-style bg=yellow
%endif

