# Set my editor and terminal
export TERMINAL=urxvtc
export EDITOR=vim
export LANG=en_US.utf8
export LC_ALL=en_US.utf8

if [ -f ~/.shell_pathes ]; then
    source ~/.shell_pathes
fi

# Host Specific Settings
if [ -f ~/.host-specific/shell_pathes ]; then
    source ~/.host-specific/shell_pathes
fi

# Some X Stuff
xsetroot -solid "#111"
ulimit -c unlimited

# Startup applications
#/usr/lib/deja-dup/deja-dup/deja-dup-monitor &
#/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
/usr/lib/notification-daemon/notification-daemon &
(sleep 8; start-pulseaudio-x11) &
(sleep 60; update-notifier) &
#(sleep 5; gnome-sound-applet) &
(sleep 5; nm-applet) &
(sleep 5; system-config-printer-applet) &
#(sleep 5; nitrogen --restore) &
#gtk-theme-switch2 -i Ambiance
xrdb -merge $HOME/.Xresources

# Disable bell
xset -b

# Host Specific Settings
if [ -f $HOME/.host-specific/xsession ]; then
    source $HOME/.host-specific/xsession
fi

# Start terminal daemon
urxvtd -f -o

# Make the i3 config

make_i3_config > $HOME/.config/i3/config

exec i3
