# Set my editor and terminal
export TERMINAL=urxvt
export EDITOR=vim

if [ -f ~/.shell_pathes ]; then
    source ~/.shell_pathes
fi

# Host Specific Settings
if [ -f ~/.host-specific/shell_pathes ]; then
    source ~/.host-specific/shell_pathes
fi

# Some X Stuff
xsetroot -solid "#333333"
ulimit -c unlimited

# Startup applications
/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
/usr/lib/notification-daemon/notification-daemon &
(sleep 8; start-pulseaudio-x11) &
(sleep 60; update-notifier) &
(sleep 5; gnome-sound-applet) &
(sleep 5; nm-applet) &
(sleep 5; system-config-printer-applet) &
#eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
(sleep 5; nitrogen --restore) &
gtk-theme-switch2 -i Ambiance
xrdb $HOME/.Xresources

# Host Specific Settings
if [ -f $HOME/.host-specific/xsession ]; then
    source $HOME/.host-specific/xsession
fi

# Make the i3 config

make_i3_config > $HOME/.config/i3/config

if [ -x ~/dev/i3/i3 ]; then
    exec ~/dev/i3/i3
else
    exec i3
fi
