# Set my editor and terminal
export TERMINAL=urxvtc
export EDITOR=vim
export LANG=en_US.utf8
export LC_ALL=en_US.utf8

systemctl --user import-environment DISPLAY PATH

if [ -f ~/.shell_pathes ]; then
    source ~/.shell_pathes
fi

# Host Specific Settings
if [ -f ~/.host-specific/shell_pathes ]; then
    source ~/.host-specific/shell_pathes
fi

# Some X Stuff
xsetroot -solid "#111"
ulimit -c unlimited
setxkbmap -option compose:menu

# Startup applications
xrandr --dpi 96
xrdb -merge $HOME/.Xresources
#/usr/lib/deja-dup/deja-dup/deja-dup-monitor &
#/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
/usr/lib/notification-daemon/notification-daemon &
(sleep 8; start-pulseaudio-x11) &
#(sleep 60; update-notifier) &
#(sleep 5; gnome-sound-applet) &
(sleep 5; nm-applet) &
(sleep 5; system-config-printer-applet) &
#(sleep 5; nitrogen --restore) &
#gtk-theme-switch2 -i Ambiance
(sleep 10; redshift-gtk) &
#(sleep 10; dropbox start) &

# Disable bell
xset -b

# Host Specific Settings
if [ -f ~/.host-specific/xsession ]; then
    source ~/.host-specific/xsession
fi

# Start terminal daemon
urxvtd -q -f -o

# Make the i3 config

make_i3_config > $HOME/.config/i3/config


exec i3
