#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

# Load this first or the work desktop cries
source ~/.host-specific/zshrc

autoload -U compinit
compinit

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
#setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
#setopt APPEND_HISTORY
## for sharing history between zsh processes
#setopt INC_APPEND_HISTORY
#setopt SHARE_HISTORY

## never ever beep ever
#setopt NO_BEEP

## automatically decide when to page a list of completions
#LISTMAX=0

## disable mail checking
#MAILCHECK=0

# autoload -U colors
colors

# Fix keys
bindkey 'OH' beginning-of-line
bindkey '[1~' beginning-of-line
bindkey 'OF' end-of-line
bindkey '[4~' end-of-line
bindkey '[3~' delete-char

zstyle ':completion:*' completer _complete _ignored _files

source ~/.bash_aliases
source ~/.host-specific/bash_aliases

[[ -a ~/.shell_pathes ]] && source ~/.shell_pathes
[[ -a ~/.host-specific/shell_pathes ]] && source ~/.host-specific/shell_pathes

