# vim:ft=yaml

rules:
  - name: Desk
    outputs_connected: 
      - DP-1-SAM-3891-809054789-U32J59x-HCRY200188
    configure_command: ~/.screenlayout/desk.sh 


  - name: Fallback
    primary: eDP-1
    configure_single: eDP-1@1920x1080
